set expandtab
au BufEnter Makefile set expandtab!
set tabstop=4
set ai

syntax on
colorscheme default

set nospell
au BufEnter *.txt,*.tex,*.md,*.rst set spell spelllang=en_us
au BufEnter *.txt,*.tex,*.md,*.rst set spellfile=~/Git/templates/vim/myDict.utf-8.add

set textwidth=79
set wrapmargin=2
