set expandtab
set tabstop=4
set textwidth=79
set ai

set ruler

syntax on
colorscheme default

set showcmd
set is hls
noh

set belloff=all

set nospell
au BufEnter *.txt,*.tex,*.md,*.rst set spell spelllang=en_us
    \ spellfile=~/Git/templates/vim/thchang.en.utf-8.add

au BufEnter Makefile set expandtab! textwidth=9999
